version: '3'

services:
  kmeans-master:
    image: docker.io/bitnami/golang:1.19
    container_name: km-master
    stdin_open: true # docker run -i
    tty: true # docker run -t
    expose:
      - '9001'
    ports:
      - '9001:9001'
    command: sh src/kmeans-MR/init.sh master
    volumes:
      - ./node:/go/src/kmeans-MR
      - ./utils:/go/src/kmeans-MR/utils
      - ./datasets:/go/src/kmeans-MR/datasets

  mapper:
    image: docker.io/bitnami/golang:1.19
    stdin_open: true # docker run -i
    tty: true # docker run -t
    expose:
      - '9999'
    depends_on:
      - kmeans-master
    command: sh src/kmeans-MR/init.sh mapper
    volumes:
      - ./node:/go/src/kmeans-MR
      - ./utils:/go/src/kmeans-MR/utils

  reducer:
    image: docker.io/bitnami/golang:1.19
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - kmeans-master
    expose:
      - '9999'
    command: sh src/kmeans-MR/init.sh reducer
    volumes:
      - ./node:/go/src/kmeans-MR
      - ./utils:/go/src/kmeans-MR/utils
