---
- hosts: all
  vars:
    local_app_dir: "../../KMeans-MR"
    remote_home: "/home/ec2-user"
    remote_app_dir: "{{ remote_home}}"  
  become: true

  tasks:
    - name: Upload KMeans Lib
      ansible.builtin.synchronize:
        src: "{{ local_app_dir }}"
        dest: "{{ remote_app_dir }}"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.gitignore"
      tags:
       - upload

    - name: Upload KMeans Lib
      ansible.builtin.synchronize:
        src: "{{ local_app_dir }}/datasets"
        dest: "{{ remote_app_dir }}/KMeans-MR"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.gitignore"
      tags:
       - datasets

    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Install Docker
      become: true
      ansible.builtin.yum:
        name: docker
        state: present 
      tags:
       - docker

    - name: Start docker service
      become: true
      ansible.builtin.command: sh {{ remote_app_dir }}/KMeans-MR/aws/docker_install.sh
      tags:
       - docker